### ISSUE TITLE
Activity feed doesn't show me when I join an idea as collaborator. 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#167]
I joined the idea +3 as collaborator. But the activity feed does not display this action.

**Comment by mkind** [comment]
Yes, from the technical perspective this is intended behavior. If a collaborator is added to an idea, the activity feed sees, that the idea is updated. But, it is not able to distinguish what is updated exactly. However, the activity feed does not show updates, because they kinda spam the activity feed. 

If we really want the activity stream to show precisely what kind of update happened, we should put it in a separate user story.

**Comment by gereonrahnfeld** [comment]
alright. 
But is it possible to show in the activity feed when sth is updated, as for example a new collaborator is added, without precisely naming this action? So sth like: 'ggr updated proposal +3'. That would be fantastic.

**Comment by slomo** [comment]
That would be already right now possible. But was that intended? Because as @mkind mentioned that might result in a lot of those activities within the stream.

**Comment by gereonrahnfeld** [comment]
I understand. Given the fact that we decided that the activity stream only displays 10 actions max. let us stick to showing no updates. 
I will close the issue.
