### ISSUE TITLE
Freetextfilter for coutry does not work

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#264]

**Comment by fuzzylogic2000** [comment]
Wouldn't it be a better idea, to add another filter to filter for countries?

It is true, that there is a bug with the freetextfilter: it does not find the projects in Germany, when I search for 'Germany', because it only knows, that there is 'de' in the database. We could fix that by getting the country list, and then trying to replace the search term for the country-fields. But to me this seems to be more complicated than just adding a country filter. Also, I think we need to (or will) rethink searching through ALL the fields in the freetextfilter, when we imported all the old ideas. I imported only about 50, and when I test the filters it's already nearly impossible to use the freetextfilter in a way, that gives me results that make sense.

**Comment by MagdaN** [comment]
@fuzzylogic2000 I agree! @gereonrahnfeld should we then add another filter for country?

**Comment by gereonrahnfeld** [comment]
I would do so. I think MitOst was very eager to be able to filter for countries. So let's do it. 
I only hope that it still looks alright if we add another filter.

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld @MagdaN Ok, I am trying to implement a country filter, but aside from me not getting it to work, we should think about what to filter exactly (again)!
There are five (!) field in the model, that could have a country. None are required. The field that was in the freetextfilter and not found was 'organisation_country', which can be chosen from the list of European countries. For the three partner_organisations, there can also be a country chosen from the same list. But the country, the idea takes place in, has to be added to the field 'idea_location_specify', which is text field and can also include cities or multiple countries or whatever the applicants think is a location. 
Initially, I thought, we should search for the 'organisation_country', which we always wanted to find in our tests of the filter (with our test data). But I think, that it would make more sense to filter for the idea location, because that is much more important than the country the organisation is from. Seeing the real imported ideas on dev, of the eleven winners, we imported this far, seven filled out the location-field with multiple countries, two also put 'Europe' in there.
What do we do? 

- If we are fine with just finding the countries in the location-field with the freetext filter, we could leave everything like that. Or we add another filter with a dropdown of the European countries, but filter the location-field. Or we add another freetext-filter to filter for location (users could also put cities or something like 'internet' in there), but that would need some help-text.

- Elif we want to always filter for all countries in all fields, this gets a bit complicated. We should also test if we want to keep the freetextfilter like that, when we imported all the ideas.

**Comment by gereonrahnfeld** [comment]
@fuzzylogic2000 @MagdaN : I agree that filtering for the country where the project should take place is the most important. However, and we discussed this shortly the last time we met Christina from MitOst, adding a new filter could be a bit too much. Christina wanted to look into this until Wednesday. I would wait until she gives us an answer. 
To create another filter to filter for a field that is not mandatory would be a problem, indeed, from my perspective.

**Comment by gereonrahnfeld** [comment]
will become a US
