### ISSUE TITLE
styling for notification when user is invited to collaborate

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#267]
The notification that is sent via email when a user is invited to collaborate needs styling. 

see designs: mailNotifications_01

![notification](https://user-images.githubusercontent.com/15954895/29315422-89ac4704-81c3-11e7-993e-993b7f9c4440.png)

**Comment by MagdaN** [comment]
Is this an issue or a user story. I know that we talked about that the styling of emails needs to be done and I think we added a user story.

**Comment by gereonrahnfeld** [comment]
@MagdaN : We have the US #84 in Advocate Europe backlog which is for the styling of notification for submitted idea. Does this automatically solve the styling issues for other notifications as well?

**Comment by MagdaN** [comment]
@gereonrahnfeld I would say so

**Comment by rukala** [comment]
I tested this notification an am missing the advocate europe logo
<img width="623" alt="bildschirmfoto 2017-09-19 um 17 34 34" src="https://user-images.githubusercontent.com/11075214/30600863-d2818120-9d60-11e7-8b56-55ad9c395316.png">

**Comment by mkind** [comment]
Good finding. Two points:

1. Either the image is just not rendered, because your mail tool prevents foreign resources for security reasons. If so, there should be an info by your mail tool. 
2. The image is not sent. If so, it might be fixed by this pull request https://github.com/liqd/a4-advocate-europe/pull/427. AFAIK this is already merged. So one should check whether this is still an issue.
