### ISSUE TITLE
#777: combine highlighting function with other functions

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#850]
The highlighting function works well. I also like the new wagtail editor. One thing that would be very awesome on top would be if the highlighting function could be combined with other functions as for example Heading 2. 
Would that be easy to do? If not we will not do it. 

![screenshot 2019-02-18 at 09 51 10](https://user-images.githubusercontent.com/15954895/52939050-7c32e580-3363-11e9-8629-3a9bcfc8ea39.png)

**Comment by fuzzylogic2000** [comment]
I couldn't find an easy fix. And I think there shouldn't be one, because the headlines, lists and also the blockquote are blocks, while bold and italic are inline-styles. So the inline-styles can be used in blocks, but not blocks in blocks. Headlines or lists can't also be used in other (normal) paragraphs. (nor can't headlines in lists.)
We could make the quote-thing an inline-style, but then we could only make it marked yellow and it wouldn't be displayed as the nice block its now.
I will close the issue, but tag @MagdaN in case she's got another idea.
